export const USER_REQUEST = "USER_REQUEST";
export const USER_FAILURE = "USER_FAILURE";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SAVE_DETAILS = "SAVE_DETAILS";
